import { Inter } from "next/font/google";
import { Web3Provider } from "@/context/Web3Context";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Web3Provider>
        <Navbar/>
        {children}
      </Web3Provider></body>
    </html>
  );
}
